### PR TITLE
add splunk-connect-for-kubernetes chart

### PR DESCRIPTION
**Pull request by cabrinha**

### CODE REVIEW

**Comment by rimusz** [comment]
Hi @cabrinha thank you for the PR.
Are you owner the repo? I do not see you as a listed maintainer there in the chart

**Comment by cabrinha** [comment]
> Hi @cabrinha thank you for the PR.
> Are you owner the repo? I do not see you as a listed maintainer there in the chart

I'm not the repo owner, but chartcenter needs to find a way for others to get charts added. I'm not sure who the repo owner is.

**Comment by rimusz** [comment]
We allow only owners to add they helm repositories.

**Comment by rockb1017** [comment]
Hello, @rimusz 
I am one of admin of that repo. 
Can I just provide approval for this or do you require me to create a new PR?

**Comment by rimusz** [comment]
@rockb1017 your approval will do

**Comment by rockb1017** [comment]
great. I approve this!

**Review by rimusz — APPROVED** [review]
LGTM

**Pull request merged**
