### PR TITLE
Adds vector latest and nightly

### PR DESCRIPTION
**Pull request by eeyun**
Signed-off-by: Ian Henry <ianjhenry00@gmail.com>

### CODE REVIEW

**Review by rimusz — APPROVED** [review]
LGTM

**Comment by rimusz** [comment]
thanks for the PR, please add `type: helm` to both, thanks

**Comment by rimusz** [comment]
@eeyun please add `type: helm` to both, thanks

**Comment by eeyun** [comment]
Sorry @rimusz. I'm confused - these additions are to the helm-hub-repos.yaml and it doesn't seem like any entries here have a type?

**Comment by rimusz** [comment]
@eeyun as per our docs you need to do the PR to `repos.yaml` the `helm-hub-repos.yaml` is just the reference what was included from the Helm Hub before it got shut down.

**Review by rimusz — CHANGES_REQUESTED** [review]
Please do changes to `repos.yaml`

**Comment by rimusz** [comment]
@eeyun would you mind to sign the CLA, thanks

**Comment by eeyun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by eeyun** [comment]
recheckcla

**Comment by eeyun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
